# Generated by Django 4.1.7 on 2023-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navlink',
            name='path',
        ),
        migrations.AddField(
            model_name='navlink',
            name='destination',
            field=models.CharField(default='', max_length=100, verbose_name='Destination (View Name or External link)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navlink',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Is Link External Link ? '),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='link_type',
            field=models.CharField(choices=[('0', 'Navbar'), ('1', 'Footer Links'), ('2', 'Footer Social')], max_length=2, verbose_name='Link Type'),
        ),
    ]
