# Generated by Django 4.1.7 on 2023-03-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Surah Name')),
                ('name_without_tashkeel', models.CharField(max_length=30, verbose_name='Surah Name Without Tashkeel')),
            ],
            options={
                'verbose_name': 'Surah',
                'verbose_name_plural': 'Surahes',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_pk', models.CharField(max_length=8, unique=True, verbose_name='Verse Primary Key')),
                ('page', models.PositiveIntegerField(verbose_name='Page')),
                ('the_quarter', models.PositiveIntegerField(verbose_name='The Quarter')),
                ('juz', models.PositiveIntegerField(verbose_name='Juz')),
                ('verse', models.CharField(max_length=5000, verbose_name='Verse')),
                ('verse_without_tashkeel', models.CharField(max_length=1000, verbose_name='Verse Without Tashkeel')),
                ('number_in_surah', models.PositiveIntegerField(verbose_name='Verse Number In Surah')),
                ('number_in_quran', models.PositiveIntegerField(unique=True, verbose_name='Verse Number In Quran')),
                ('is_sajda', models.BooleanField(verbose_name='Is the verse a sajda?')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='verses.surah', verbose_name='Surah')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
            },
        ),
    ]
