# Generated by Django 5.0.4 on 2026-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Audio File Name')),
                ('url', models.URLField(verbose_name='Audio File URL')),
            ],
        ),
        migrations.AddField(
            model_name='verse',
            name='audio',
            field=models.ManyToManyField(blank=True, to='verses.audio'),
        ),
    ]
