# Generated by Django 5.0.4 on 2026-02-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_audio_verse_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.IntegerField(unique=True, verbose_name='Phrase ID')),
                ('surahs_count', models.IntegerField(verbose_name='Surahs Count')),
                ('ayahs_count', models.IntegerField(verbose_name='Ayahs Count')),
                ('occurrences_count', models.IntegerField(verbose_name='Occurrences Count')),
                ('source_word_from', models.IntegerField(verbose_name='Source Word From')),
                ('source_word_to', models.IntegerField(verbose_name='Source Word To')),
                ('source_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_phrases', to='verses.verse', verbose_name='Source Verse')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
            },
        ),
        migrations.CreateModel(
            name='PhraseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_from', models.IntegerField(verbose_name='Word From')),
                ('word_to', models.IntegerField(verbose_name='Word To')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='verses.phrase', verbose_name='Phrase')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_occurrences', to='verses.verse', verbose_name='Verse')),
            ],
            options={
                'verbose_name': 'Phrase Occurrence',
                'verbose_name_plural': 'Phrase Occurrences',
            },
        ),
    ]
