# Generated by Django 4.1.7 on 2024-03-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_radio_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Radio Rank'),
        ),
    ]
