# Generated by Django 4.1.7 on 2023-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_set_category_rank_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Category Rank'),
        ),
    ]
