# Generated by Django 4.1.7 on 2023-04-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_category_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['rank'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
