# Generated by Django 4.1.7 on 2024-03-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_alter_radio_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radio',
            options={'ordering': ['rank']},
        ),
    ]
