# Generated by Django 5.0.4 on 2024-06-04 21:58

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_alter_radio_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
