# Generated by Django 5.0.4 on 2026-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_alter_radio_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddField(
            model_name='radio',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='radio',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Views Count'),
        ),
    ]
