# Generated by Django 4.1.7 on 2023-04-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_remove_radio_categories_radio_categories_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radio',
            old_name='categories_new',
            new_name='categories',
        ),
    ]
