# Generated by Django 4.1.7 on 2023-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Radio Name')),
                ('stream_url', models.URLField(verbose_name='Radio Stream URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Radio Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='radio/', verbose_name='Radio Image')),
                ('categories', models.ManyToManyField(blank=True, related_name='radios', to='radio.category', verbose_name='Radio Categories')),
            ],
        ),
    ]
