# Generated by Django 4.1.7 on 2023-04-07 00:24

from django.db import migrations


def copy_relations_to_new_table(apps, schema_editor):
    """
    Set Category Value Rank To  Category Id as initial value
    """
    Category = apps.get_model('radio', 'Category')
    RadioCategoriesM2M = apps.get_model('radio', 'RadioCategoriesM2M')
    for category in Category.objects.all():
        rank = 1
        for radio in category.radios.all():
            rel = RadioCategoriesM2M(radio=radio, category=category, rank=rank)
            rel.save()
            rank += 1


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_radiocategoriesm2m'),
    ]

    operations = [
        migrations.RunPython(copy_relations_to_new_table)
    ]
