# Generated by Django 4.1.7 on 2023-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_copy_radio_categories_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='categories',
        ),
        migrations.AddField(
            model_name='radio',
            name='categories_new',
            field=models.ManyToManyField(blank=True, related_name='radios', through='radio.RadioCategoriesM2M', to='radio.category', verbose_name='Radio Categories'),
        ),
    ]
